"""Realistic canned agent outputs for the california-housing task.

Generated by acting as the LLM against the actual agent prompts (the
data_analyst digest + the plan_author instruction with the allowed vocabulary),
so offline tests exercise *realistic* output without any API call. Regenerate by
feeding make_data_summary(...) + the agent instructions to any capable model.
"""

# data_analyst -> state["dataset_analysis"]
DATASET_ANALYSIS = """\
Task: regression, target 'median_house_value' (continuous, scored by RMSE).

Column types:
- All 8 features are numeric (float64) with 0% missing values. There are no
  categorical, text, or datetime columns, so the high-cardinality encoder
  choice (GapEncoder vs MinHashEncoder) is NOT relevant for this dataset.
- median_income, total_rooms, total_bedrooms, population and households are
  right-skewed with wide ranges (total_rooms up to ~30k). Tree models handle
  this natively; linear models benefit from robust scaling.
- longitude/latitude are geographic; ratio/interaction features
  (rooms-per-household, population-per-household) are known to lift signal.

Options worth searching per stage:
- clean: skip (data is clean) vs a light Cleaner.
- scale: skip vs StandardScaler vs RobustScaler (RobustScaler given the skew).
  Matters mostly for the linear model.
- feature engineering: skip vs PolynomialFeatures (degree 2) for income x
  geography interactions.
- model: HistGradientBoosting (strong tabular-regression default),
  RandomForest (robust baseline), Linear/Ridge (scaled-features comparator).
"""

# plan_author -> state["skrub_spec_raw"]  (dotted paths + tuned HPs; valid JSON)
SKRUB_SPEC_RAW = """\
{
  "clean_options": ["skip", "skrub.Cleaner"],
  "stages": [
    {"name": "scale", "options": ["skip", "sklearn.preprocessing.StandardScaler", "sklearn.preprocessing.RobustScaler"]},
    {"name": "feature_eng", "options": ["skip",
      {"name": "sklearn.preprocessing.PolynomialFeatures", "params": {"degree": {"int": [2, 3]}}}]}
  ],
  "model": [
    {"name": "sklearn.ensemble.HistGradientBoostingRegressor", "params": {
       "learning_rate": {"float": [0.01, 0.3], "log": true},
       "max_iter": {"int": [100, 600]},
       "max_depth": {"int": [2, 16]}}},
    {"name": "sklearn.ensemble.RandomForestRegressor", "params": {
       "n_estimators": {"int": [100, 500]},
       "max_depth": {"int": [3, 30]}}},
    "sklearn.linear_model.Ridge"
  ]
}
"""

# Convenience: the two model turns in call order, for a scripted fake model.
RESPONSES = [DATASET_ANALYSIS, SKRUB_SPEC_RAW]
